/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package P1R.Garcia;

/**
 *
 * @author richard
 */
public class practica1 extends javax.swing.JFrame {

    /**
     * Creates new form practica1
     */
    public practica1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        coches = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        buses = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cam_liv = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        cam_pes = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        suma = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cantidad = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        cantidadbus = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        cantidadcamliv = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        cantidadcampes = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        cantidadliv = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        tot1 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        tot2 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        tot3 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        tot4 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        tot5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("materia:desarrollo de Software II");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 11, 218, 18));

        jLabel2.setText("profesor:Andy Gomez De La Torre ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 35, 179, -1));

        jLabel3.setText("nombre del projecto: P1R.garcia");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 55, 196, -1));

        jLabel4.setText("programador:Richard Garcia (4-808-563)");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 75, -1, -1));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Bell MT", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 153, 0));
        jLabel5.setText("      Peajes Garcia");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 107, 510, 33));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("veiculos livianos 2.30");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 197, 28));

        coches.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cochesActionPerformed(evt);
            }
        });
        getContentPane().add(coches, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, 110, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("buses                     5.30");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 197, 28));

        buses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                busesActionPerformed(evt);
            }
        });
        getContentPane().add(buses, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 200, 110, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("camiones livianos  3.35");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 240, 210, 28));

        cam_liv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cam_livActionPerformed(evt);
            }
        });
        getContentPane().add(cam_liv, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 240, 110, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("camiones pesados 7.00");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, 210, 28));

        cam_pes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cam_pesActionPerformed(evt);
            }
        });
        getContentPane().add(cam_pes, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 280, 110, 30));

        jButton1.setText("guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 350, 120, 30));
        getContentPane().add(suma, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 420, 100, -1));
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 410, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("cantidad de veiculos");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 500, 210, 20));

        cantidad.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cantidad.setText("0");
        getContentPane().add(cantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 500, 90, 20));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("cantidad de buses");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 410, 210, 30));

        cantidadbus.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cantidadbus.setText("0");
        getContentPane().add(cantidadbus, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 410, 80, 30));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setText("cantidad de camiones livianos");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 270, 30));

        cantidadcamliv.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cantidadcamliv.setText("0");
        getContentPane().add(cantidadcamliv, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 440, 60, 30));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setText("cantidad de camiones pesados");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 280, 30));

        cantidadcampes.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cantidadcampes.setText("0");
        getContentPane().add(cantidadcampes, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 470, 60, 30));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setText("cantidad de veiculos livianos");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 290, 20));

        cantidadliv.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cantidadliv.setText("0");
        getContentPane().add(cantidadliv, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 390, 70, 20));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setText("total veiculos livianos");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 390, 200, 20));

        tot1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tot1.setText("0");
        getContentPane().add(tot1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 390, 70, 20));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setText("total buses");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 420, 200, 20));

        tot2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tot2.setText("0");
        getContentPane().add(tot2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 420, 70, 20));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel18.setText("total camines livianos");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 450, 200, 20));

        tot3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tot3.setText("0");
        getContentPane().add(tot3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 450, 70, 20));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel19.setText("total camiones pesados");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 480, 220, 20));

        tot4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tot4.setText("0");
        getContentPane().add(tot4, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 480, 70, 20));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel20.setText("total");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 500, 50, 20));

        tot5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tot5.setText("0");
        getContentPane().add(tot5, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 500, 70, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cochesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cochesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cochesActionPerformed

    private void busesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_busesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_busesActionPerformed

    private void cam_livActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cam_livActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cam_livActionPerformed

    private void cam_pesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cam_pesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cam_pesActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String coche = coches.getText();
        int coche2=Integer.parseInt(coche);
         String bus = buses.getText();
        int bus2=Integer.parseInt(bus);
         String camliv = cam_liv.getText();
        int camliv2=Integer.parseInt(camliv);
        String campes = cam_pes.getText();
        int campes2=Integer.parseInt(campes);
        
       int sum=coche2+bus2+camliv2+campes2;
       String suma2= sum+"";
    cantidad.setText(suma2);
    cantidadbus.setText(bus);
    cantidadcamliv.setText(camliv);
    cantidadcampes.setText(campes);
    cantidadliv.setText(coche);
    double precio1 = 2.30*coche2;
    String precioco=precio1+"";
    double precio2= 5.30*bus2;
    String preciobu=precio2+"";
    double precio3= 3.35*camliv2;
    String preciocam1=precio3+"";
    double precio4=7.00*campes2;
    String preciocam2=precio4+"";
    double tot=precio1+precio2+precio3+precio4;
    String total=tot+"";
    tot1.setText(precioco);
    tot2.setText(preciobu);
    tot3.setText(preciocam1);
    tot4.setText(preciocam2);
    tot5.setText(total);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(practica1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(practica1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(practica1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(practica1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new practica1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField buses;
    private javax.swing.JTextField cam_liv;
    private javax.swing.JTextField cam_pes;
    private javax.swing.JLabel cantidad;
    private javax.swing.JLabel cantidadbus;
    private javax.swing.JLabel cantidadcamliv;
    private javax.swing.JLabel cantidadcampes;
    private javax.swing.JLabel cantidadliv;
    private javax.swing.JTextField coches;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel suma;
    private javax.swing.JLabel tot1;
    private javax.swing.JLabel tot2;
    private javax.swing.JLabel tot3;
    private javax.swing.JLabel tot4;
    private javax.swing.JLabel tot5;
    // End of variables declaration//GEN-END:variables
}
